[global]
# Streamlit Cloud configuration

[server]
# Server configuration for cloud deployment
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
# Browser configuration
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
# Theme configuration for better appearance
primaryColor = "#3b82f6"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
textColor = "#1f2937"
font = "sans serif"

[runner]
# Performance optimization
magicEnabled = true
installTracer = false
fixMatplotlib = true

[client]
# Client configuration
caching = true
displayEnabled = true
showErrorDetails = true
